from django.urls import path
from . import views
from .views import *
from django.views.generic import TemplateView

urlpatterns = [
    path('', views.home, name='website-home'),
    # path('cancer_units/<int:pk>/', views.cancer_units, name='website-cancer_units'),
    path('cancer_units/', views.cancer_units, name='website-cancer_units'),
    path('cancer_experts/', views.cancer_experts, name='website-cancer_experts'),
    path('cancer_networks/', views.cancer_networks, name='website-cancer_networks'),
    path('cancer_organizations/', views.cancer_organizations, name='website-cancer_organizations'),
    path('cancer_experts_info/<int:item_id>', views.cancer_experts_info, name='website-cancer_experts_info'),
    path('cancer_organizations_info/<int:item_id>', views.cancer_organizations_info, name='website-cancer_organizations_info'),
    path('cancer_networks_info/<int:item_id>', views.cancer_networks_info, name='website-cancer_networks_info'),
    path('cancer_units_info/<int:item_id>', views.cancer_units_info, name='website-cancer_units_info'),
    path('cancer_types_info/<int:item_id>', views.cancer_types_info, name='website-cancer_types_info'),
    path('donate/<int:item_id>', views.donate, name='website-donate'),
    path('mobile_money/<int:item_id>', views.mobile_money, name='website-mobile_money'),
    path('pay/<int:item_id>', views.pay, name='website-pay'),
    path('give_gift/<int:item_id>', views.give_gift, name='website-give_gift'),
    path('pay_via_bank/<int:item_id>', views.pay_via_bank, name='website-pay_via_bank'),
    path('fundraiser/', views.fundraiser, name='website-fundraiser'),
    # path('crowdfunding_donation/', views.crowdfunding_donation, name='website-crowdfunding_donation'),
    path('video/', views.video, name='website-video'),
    path('cancer_types/', views.cancer_types, name='website-cancer_types'),
    path('infographics/', views.infographics, name='website-infographics'),
    path('presentation/', views.presentation, name='website-presentation'),
    path('keynotes/', views.keynotes, name='website-keynotes'),
    path('faqs/', views.faqs, name='website-faqs'),
    path('crowdfunding/', views.crowdfunding, name='website-crowdfunding'),
    # path('unit/', views.unit, name='unit'),
    # path('cancer_units/<int:pk>/operationstatus', views.operation_status, name='website-operation-status'),
    # path('cancer_units/<int:pk>/founder', views.founder, name='website-founder'),
    # path('cancer_units/<int:pk>/funder', views.funders, name='website-funder'),
    # path('cancer_units/<int:pk>/category', views.category, name='website-categories'),
    # path('cancer_units/<int:pk>/section', views.section, name='website-sections'),
    # path('cancer_units/<int:pk>/reg_status', views.registration_status, name='website-registration-status'),
    # path('cancer_units/<int:pk>/access', views.access, name='website-accesses'),
    # path('cancer_units/<int:pk>/urban', views.rural_urban, name='website-rural-urban'),
    # path('cancer_units/<int:pk>/nearest_unit', views.nearest_unit, name='website-nearest-unit'),
    # path('cancer_units/<int:pk>/nearest_deo', views.nearest_deo, name='website-nearest-deo'),
    # path('teachers/', views.teachers, name='website-teachers'),
    # path('DEOs/', views.deos, name='website-deos'),
    # path('results/', views.results, name='website-results'),
    # path('marketing/', views.marketing, name='website-marketing'),
    # path('service_providers/', views.service_providers, name='service-providers'),
    # path('apply/', views.apply, name='apply'),
    # path('covid19/', views.covid19, name='covid19'),
    # path('report/', views.report, name='report'),
    # path('covid19_downloads/<int:pk>/', views.covid19_downloads, name='covid19-downloads'),
    # path('communication/', views.communication, name='website-communication'),
    # path('resources/', views.resources, name='website-resources'),
    # path('results_uace/', views.uace_results, name='results-uace'),
    # path('results_uce/', views.uce_results, name='results-uce'),
    # path('results_ple/', views.ple_results, name='results-ple'),
    path('settings/', views.settings, name='website-settings'),
    path('slider/', SliderTemplate.as_view(), name='slider'),
    path('slider_main/', SliderMainTemplate.as_view(), name='slider-main'),
    path('search_google/', views.search_google, name='search-google'),

]
